services:
  postgres:
    container_name: postgres-sql-wac
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: whatsapp_clone
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - whatsapp_clone
    restart: unless-stopped
  backend:
    container_name: whatsapp-clone-backend
    build:
      context: ./whatsappclone
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/whatsapp_clone
      KEYCLOAK_URL: http://192.168.1.104:8080
    ports:
      - 1234:1234
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - whatsapp_clone
  frontend:
    container_name: whatsapp-clone-frontend
    build:
      context: ./whatsapp-clone-ui
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    restart: unless-stopped
    networks:
      - whatsapp_clone

networks:
  whatsapp_clone:
    driver: bridge
    
volumes:
  postgres:
    driver: local